name: Update main branch from react dist

on:
  push:
    branches:
      - react

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "vini.gazzana@gmail.com"

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          cache: "yarn"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Checkout react branch
        run: git checkout react

      - name: Yarn Install
        run: yarn install

      - name: Build react app
        run: yarn build

      - name: Copy dist files to temporary location
        run: mkdir temp && cp -r dist/* temp/

      - name: Checkout main branch
        run: git checkout main

      - name: Copy dist files to main branch
        run: cp -r temp/* .

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Update main from react dist"

      - name: Push changes
        run: git push
